const message = {
  resetTokenExpired: 'Sorry, your reset password link is expired',
  successfulRegister: 'User has been registered successfully',
  serverErr: 'Internal server error',
  invalidEmail: 'Email must be valid',
  alreadyRegisterEmail: 'Email has been already registered',
  minPassword: 'Password should be 7 characters long',
  invalidEmailorPassword: 'Invalid Email or Password',
  notAuthenticated: 'User is not authenticated',
  invalidId: 'Invalid id',
  successfulLogin: 'User has been successfully logged in',
  successLogout: 'You are successfully logged out',
  updateAddress: 'Address has been updated successfully',
  unauthorized: 'Unauthorized access',
  tokenErr: 'Authorization token is not valid',
  alreadyRegisterAuth: 'User already exists with this authId',
  wrongRole: 'Role does not exists',
  updatePassword: 'Password has been updated successfully',
  updateUser: 'User has been updated successfully',
  userExists: 'This authId is already registered',
  invalidAuthId: 'Invalid authId',
  userNotExists: 'User does not exists',
  updateProfile: 'Profile has been updated successfully',
  noOldPasswordMatch: 'It seems that your old password is incorrect',
  userDeletedByAdmin: 'This user has been deleted by admin. Please contact to admin.',
  isuserExists: "User is already register with this phone number",
  userDeactivatedByAdmin: 'This user has been deactivated by admin. Please contact to admin.',
  incorrectEmail: 'Incorrect email',
  invalidKey: 'Spaces are not allowed in key.',
  resetPassword: 'Email has been sent to your registered email address',
};

module.exports = message;
